INSERT INTO Exercise (Name, Language) VALUES ('ChickenMonkey', 'JavaScript');
INSERT INTO Exercise (Name, Language) VALUES ('Overly Excited', 'JavaScript');
INSERT INTO Exercise (Name, Language) VALUES ('Boy Bands & Vegetables', 'JavaScript');
INSERT INTO Exercise (Name, Language) VALUES ('Car Lot', 'JavaScript');
INSERT INTO Exercise (Name, Language) VALUES ('Nashville Kennels', 'JavaScript');
INSERT INTO Exercise (Name, Language) VALUES ('Family Dictionary', 'C#');
INSERT INTO Exercise (Name, Language) VALUES ('Solar System', 'C#');
INSERT INTO Exercise (Name, Language) VALUES ('Kill Nickelback', 'C#');
INSERT INTO Exercise (Name, Language) VALUES ('Junkyard', 'C#');
INSERT INTO Exercise (Name, Language) VALUES ('Stock Ticker', 'C#');
